#!/usr/bin/env node
// Generates iOS and website icon assets from the source PNGs in marketing/logo/.
//
// iOS: two 1024x1024 universal icons — light (blue S) and dark (red S on dark
//      grey). The system swaps based on the user's iOS appearance setting.
// Website: 32x32 favicon and 180x180 Apple Touch icon.
//
// Android icons are NOT generated by this script — they're managed via
// Android Studio's Image Asset Studio, which provides interactive previews
// of how the icon renders under each launcher mask shape. To regenerate
// Android assets: open the project in Android Studio, right-click the `res/`
// folder → New → Image Asset → Launcher Icons (Adaptive and Legacy).
//
// Run: node scripts/generate-icons.mjs

import sharp from 'sharp';
import { promises as fs } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..');
const SRC_LIGHT = resolve(root, 'marketing/logo/spc - light mode - blue S.png');
const SRC_DARK  = resolve(root, 'marketing/logo/spc - dark mode - red S.png');

const iosOut = resolve(root, 'app/Assets.xcassets/AppIcon.appiconset');
const websiteOut = resolve(root, 'website');

async function generateIosIcons() {
  const SIZE = 1024;
  await sharp(SRC_LIGHT).resize(SIZE, SIZE, { fit: 'cover' }).png()
    .toFile(resolve(iosOut, 'icon_1024x1024.png'));
  console.log('  iOS light: icon_1024x1024.png');

  await sharp(SRC_DARK).resize(SIZE, SIZE, { fit: 'cover' }).png()
    .toFile(resolve(iosOut, 'icon_1024x1024_dark.png'));
  console.log('  iOS dark:  icon_1024x1024_dark.png');
}

async function writeIosContentsJson() {
  const json = {
    images: [
      {
        filename: 'icon_1024x1024.png',
        idiom: 'universal',
        platform: 'ios',
        size: '1024x1024',
      },
      {
        appearances: [{ appearance: 'luminosity', value: 'dark' }],
        filename: 'icon_1024x1024_dark.png',
        idiom: 'universal',
        platform: 'ios',
        size: '1024x1024',
      },
    ],
    info: { author: 'xcode', version: 1 },
  };
  await fs.writeFile(
    resolve(iosOut, 'Contents.json'),
    JSON.stringify(json, null, 2) + '\n'
  );
  console.log('  iOS Contents.json updated (light + dark)');
}

async function generateWebsiteIcons() {
  // Standard favicon (used by browsers, RSS readers, link previews).
  await sharp(SRC_LIGHT).resize(32, 32, { fit: 'cover' }).png()
    .toFile(resolve(websiteOut, 'favicon.png'));
  console.log('  Web: favicon.png (32x32)');

  // Apple touch icon (iOS Add to Home Screen, Safari pinned tabs).
  await sharp(SRC_LIGHT).resize(180, 180, { fit: 'cover' }).png()
    .toFile(resolve(websiteOut, 'apple-touch-icon.png'));
  console.log('  Web: apple-touch-icon.png (180x180)');
}

async function main() {
  console.log(`Light source: ${SRC_LIGHT}`);
  console.log(`Dark source:  ${SRC_DARK}\n`);

  console.log('Generating iOS icons…');
  await generateIosIcons();
  await writeIosContentsJson();

  console.log('\nGenerating website icons…');
  await generateWebsiteIcons();

  console.log('\nNote: Android icons are managed via Android Studio → Image Asset Studio.');
  console.log('Done.');
}

main().catch(err => {
  console.error(err);
  process.exit(1);
});
